Feature: AI assistant Virgil

  Background:
    Given a user named "0xlyd"
    And that I am logged in as 0xlyd

  Scenario: start a new conversation with Virgil
    When I want to ask Virgil something
    Then I can initiate the process
    And I can provide my query via text
    Then the system should automatically add a date
    * a time
    * an autogenerated title
    And Virgil, through an AI, should text me a reply back within 2 minutes

  Scenario: view all conversations
    When I want to check previous conversations
    Then I can access the list of previous chats with Virgil ordered by most recent

  Scenario: view a single conversation
    When I want to read through a past conversation
    Then I can select one from the list of all conversations
  
  Scenario: search previous conversation by name
    When I want to look for a conversation
    But I don't remember when it was done
    Then I should be able to search some words in the title
    And the system should return matching conversations ordered by most recent